# -*- coding: utf-8 -*-
"""
Firma Toplu Ekleme Script'i
"""
import asyncio
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database import firms_collection
from datetime import datetime
import uuid

FIRMS_TO_ADD = [
    "112 ACİL",
    "AB DENİZCİLİK",
    "ABRC İNŞAAT",
    "ABT",
    "ACD İNŞAAT",
    "ADR(KOLİN)",
    "AHTAPOT DENİZCİLİK",
    "AKAD MÜHENDİSLİK",
    "AKCANLAR VİNÇ",
    "AKIN TÜRK PETROL",
    "AKS PEYZAJ",
    "ALAGÖZLER",
    "ALATEK OTOMASYON",
    "ALBA TEK",
    "ALBERK",
    "ALCE MÜHENDİSLİK",
    "ALFANORM",
    "ALİCAN GEMİ",
    "ALKOLM",
    "ALK DENİZCİLİK",
    "ALTINTAS YEMEKÇİLİK",
    "ANKA-GRUP",
    "ANTEK ELEKTRİK",
    "ARAS DENİZ İNŞAAT",
    "ARAS KARDEŞLER",
    "ARAS MARİNE",
    "ARES",
    "ARİS OSGB",
    "ARMA",
    "ARMİN İNŞAAT",
    "ARTAŞ",
    "ASTAR",
    "ASTAŞ",
    "ATAK MÜHENDİSLİK",
    "ATALAYLAR",
    "ATLANTİK GEMİ İŞLETMECİLİĞİ",
    "ATOM ISI",
    "AVS",
    "AVRASYA",
    "AYALEN ENERJİ",
    "AYDIN KAYA GRUP",
    "AYDINTAŞ VİNÇ",
    "AYGÜNLER",
    "BABA VİNÇ",
    "BAKER HUGHES",
    "BARAN GRUP",
    "BARANKAYA",
    "BATI KARADENİZ NAKLİYE",
    "BAYER GROUP",
    "BER ÇEVRE LOJİSTİK",
    "BEŞEL LOJİSTİK",
    "BE-SAFE",
    "BİLGİNER HAZIR BETON",
    "BİRMEK",
    "BLT",
    "BNB AŞ",
    "BORTEK MÜHENDİSLİK",
    "BOZKAYA İNŞAAT",
    "BOTAŞ",
    "BORUSAN CAT",
    "BTM TEKNİK",
    "BURAKSAN",
    "CAVİTECH DENİZCİLİK",
    "CEYNAK",
    "CİHAN CENGİZ KARADENİZ GEMİ",
    "ÇAĞ PLAS",
    "ÇELİKELLER",
    "ÇELİKKOL",
    "ÇELİKOĞLU İNŞAAT",
    "ÇEŞME TURİZM BARTIN",
    "ÇETİNSA",
    "ÇEVİK KUVVET",
    "ÇİMKO",
    "DDR MÜHENDİSLİK",
    "DEHA",
    "DELTA LOJİSTİK",
    "DENAR LOJİSTİK",
    "DEGEM",
    "DENKSAN",
    "DH HARİTA",
    "DİPLOMAT GÜVENLİK",
    "DİANEM",
    "DİNÇ ELEKTRİK",
    "DORÇE",
    "DORUK ELEKTRİK",
    "DORUK İNŞAAT",
    "EDRA",
    "EFES MARİN",
    "EKA NDT",
    "EKE ENDÜSTRİ",
    "ENDOCE MÜHENDİSLİK",
    "ENERMECH-ENERTECH",
    "ENERTES",
    "ERAL",
    "ERGENÇ",
    "ERSOY",
    "ER-SU",
    "ERYA MÜHENDİSLİK",
    "ESEA",
    "ETA GRUP",
    "FATİH OFFSHORE",
    "FALCKON",
    "FIRTINA",
    "FİLYOS BELEDİYESİ",
    "FİLYOS İTFAİYE",
    "FİLYOS YAPI",
    "GALATA GRUP",
    "GEMA",
    "GEMİNİ GEMİSİ",
    "GEMSAN",
    "GİNES",
    "GNC TEAM",
    "GNR İŞ MAKİNALARI",
    "GNV AZZURA",
    "GOE PETROL",
    "GRM ENERJİ",
    "GÜN İNŞAAT",
    "GÜLTAŞ",
    "GÜNA",
    "GÜNGÖR ELEKTRİK",
    "GÜRDESAN",
    "GÜRAN",
    "GÜRAS",
    "HAREKET",
    "HEALMEDY",
    "HED AKADEMİ",
    "HCV",
    "HEDEF ISI",
    "HESA TEKNİK",
    "INTERCON",
    "IŞIKLAR AĞIR NAKLİYAT",
    "İKAN",
    "İKSA",
    "İMERE KÖYLÜOĞLU ENERJİ",
    "İMR",
    "İNDUNİT",
    "İSA AYSAN",
    "İSMAK",
    "İTFAİYE",
    "İZOFER",
    "JANDARMA",
    "KANUNİ GEMİSİ",
    "KARYAP",
    "KENT",
    "KESİR MÜHENDİSLİK",
    "KG PREFABRİK",
    "KIYI EMNİYETİ",
    "KIZILAY",
    "KIZILAY KONTEYNER",
    "KIZILTAŞ",
    "KL YAPI",
    "KOCABEY HAFRİYAT",
    "KOLİN",
    "KORKUT GEMİSİ",
    "KORTEK",
    "KOZTAŞ",
    "KSK",
    "KUZEY LOJİSTİK",
    "KUZEY MUTFAK",
    "KURTAŞ",
    "KURTOĞLU",
    "LAGAR",
    "LAM KARA-HAVA DENİZ TAŞIMACILIĞI",
    "LCM ROTA DENİZCİLİK",
    "LİVA İSKELE",
    "MAKİMSAN",
    "MAMMOET",
    "MANSUR İLETİŞİM",
    "MARE DENİZCİLİK",
    "MASTER NET",
    "MEDMARİNE",
    "META GRUP",
    "MEKTES",
    "MELİSA HAFRİYAT",
    "MERC GLOBAL",
    "METSAN",
    "MİHRİMAH GEMİSİ",
    "MMC GRUP",
    "MİM MÜHENDİSLİK",
    "MRM GAZİ",
    "MİTAŞ",
    "NET LAMİNAT",
    "NEGMAR TEKNİK DENİZCİLİK",
    "NOVA DENİZCİLİK",
    "OLCAY ENERJİ",
    "OGS",
    "OLKAR",
    "ONURSAN",
    "OPET",
    "OPTİMUM MÜHENDLİSLİK",
    "ÖZARDIÇ",
    "ÖZDEMİR YAPI",
    "ÖZLEM KURUTÇU(RÖNESANS)",
    "PİRAMİT",
    "PİRENKUŞ",
    "POLİS",
    "PR BETON",
    "PRİZMA",
    "PRODA",
    "PRAMO",
    "PROTOKOL",
    "RET",
    "RASAT İSG",
    "ROTA MÜHENDİSLİK",
    "ROVTEK",
    "ROXANEZ GEMİSİ",
    "REAL",
    "REM GRUP",
    "RÖNESANS",
    "RYS ROTA",
    "SADUNOĞLU",
    "SABNAR",
    "SAHİL GÜVENLİK",
    "SAİPEM",
    "SAKARYA OFF-SHORE",
    "SANCAR GEMİ",
    "SANKO",
    "SARDUNYA CATERİNG",
    "SARIDAĞLAR",
    "SARILAR GRUP",
    "SEBA DENİZCİLİK",
    "SEAFORT",
    "SAVÇELİK",
    "SCHLUMBERGER",
    "SİSTEM VİNÇ",
    "SİTEPLUS",
    "SOLEBAY ENERJİ",
    "SOYSAL",
    "SOLİS MÜHENDİSLİK",
    "STEELUPRO",
    "SUBSEA7",
    "ŞADAKS",
    "ŞANTİYE",
    "TCH GRUP",
    "TESTKAL",
    "TEMSAN",
    "TIMS GLOBAL",
    "TOKA PREFABRİK",
    "TOKER",
    "TOPKAPI",
    "TOSYALI",
    "TOVER SANDAŞ İNŞAAT",
    "TP GÜVENLİK-EKOL GRUP",
    "TP-OTC",
    "TUNÇKAR",
    "TÜRK LOYDU",
    "TÜRK TELEKOM",
    "ULUER",
    "UNİWORKS",
    "UNİTED OFFSHORE",
    "US MÜHENDİSLİK",
    "ÜSTÜN ENERJİ",
    "VARLI PROJE",
    "VEMAK",
    "VERİTAŞ",
    "VİYATEK",
    "VOLKAN İTFAİYE",
    "WERNER SOBEK AG-TR",
    "YAREN VİNÇ",
    "YAŞAR AKGÜN NAKLİYAT",
    "YAVUZ GEMİ",
    "YAVUZ57",
    "YIKILMAZ İNŞAAT",
    "YİĞİTHAN PROJE",
    "YOKOGAVA",
    "YUNUS AMBULANS",
    "YÜKSEL TAŞ NAKLİYAT",
    "ZAĞANOS GEMİSİ"
]

async def clear_and_add_firms():
    """Tum firmalari sil ve yeniden ekle"""
    # Once tum firmalari sil
    result = await firms_collection.delete_many({})
    print(f"Silinen firma sayisi: {result.deleted_count}")
    
    added = 0
    
    for firm_name in FIRMS_TO_ADD:
        firm_id = str(uuid.uuid4())
        now = datetime.utcnow()
        
        new_firm = {
            "_id": firm_id,
            "name": firm_name,
            "is_active": True,
            "created_at": now,
            "created_by": "system_import"
        }
        
        await firms_collection.insert_one(new_firm)
        print(f"[OK] Eklendi: {firm_name}")
        added += 1
    
    print(f"\n{'='*50}")
    print(f"Toplam eklenen: {added}")

if __name__ == "__main__":
    asyncio.run(clear_and_add_firms())
