/**
 * Firma Listesi - Vaka Kayıt Formu için
 * 268 firma
 */

export const COMPANIES = [
  { id: 1, name: '112 ACİL' },
  { id: 2, name: 'AB DENİZCİLİK' },
  { id: 3, name: 'ABRC İNŞAAT' },
  { id: 4, name: 'ABT' },
  { id: 5, name: 'ACD İNŞAAT' },
  { id: 6, name: 'ADR(KOLİN)' },
  { id: 7, name: 'AHTAPOT DENİZCİLİK' },
  { id: 8, name: 'AKAD MÜHENDİSLİK' },
  { id: 9, name: 'AKCANLAR VİNÇ' },
  { id: 10, name: 'AKIN TÜRK PETROL' },
  { id: 11, name: 'AKS PEYZAJ' },
  { id: 12, name: 'ALAGÖZLER' },
  { id: 13, name: 'ALATEK OTOMASYON' },
  { id: 14, name: 'ALBA TEK' },
  { id: 15, name: 'ALBERK' },
  { id: 16, name: 'ALCE MÜHENDİSLİK' },
  { id: 17, name: 'ALFANORM' },
  { id: 18, name: 'ALİCAN GEMİ' },
  { id: 19, name: 'ALKOLM' },
  { id: 20, name: 'ALK DENİZCİLİK' },
  { id: 21, name: 'ALTINTAS YEMEKÇİLİK' },
  { id: 22, name: 'ANKA-GRUP' },
  { id: 23, name: 'ANTEK ELEKTRİK' },
  { id: 24, name: 'ARAS DENİZ İNŞAAT' },
  { id: 25, name: 'ARAS KARDEŞLER' },
  { id: 26, name: 'ARAS MARİNE' },
  { id: 27, name: 'ARES' },
  { id: 28, name: 'ARİS OSGB' },
  { id: 29, name: 'ARMA' },
  { id: 30, name: 'ARMİN İNŞAAT' },
  { id: 31, name: 'ARTAŞ' },
  { id: 32, name: 'ASTAR' },
  { id: 33, name: 'ASTAŞ' },
  { id: 34, name: 'ATAK MÜHENDİSLİK' },
  { id: 35, name: 'ATALAYLAR' },
  { id: 36, name: 'ATLANTİK GEMİ İŞLETMECİLİĞİ' },
  { id: 37, name: 'ATOM ISI' },
  { id: 38, name: 'AVS' },
  { id: 39, name: 'AVRASYA' },
  { id: 40, name: 'AYALEN ENERJİ' },
  { id: 41, name: 'AYDIN KAYA GRUP' },
  { id: 42, name: 'AYDINTAŞ VİNÇ' },
  { id: 43, name: 'AYGÜNLER' },
  { id: 44, name: 'BABA VİNÇ' },
  { id: 45, name: 'BAKER HUGHES' },
  { id: 46, name: 'BARAN GRUP' },
  { id: 47, name: 'BARANKAYA' },
  { id: 48, name: 'BATI KARADENİZ NAKLİYE' },
  { id: 49, name: 'BAYER GROUP' },
  { id: 50, name: 'BER ÇEVRE LOJİSTİK' },
  { id: 51, name: 'BEŞEL LOJİSTİK' },
  { id: 52, name: 'BE-SAFE' },
  { id: 53, name: 'BİLGİNER HAZIR BETON' },
  { id: 54, name: 'BİRMEK' },
  { id: 55, name: 'BLT' },
  { id: 56, name: 'BNB AŞ' },
  { id: 57, name: 'BORTEK MÜHENDİSLİK' },
  { id: 58, name: 'BOZKAYA İNŞAAT' },
  { id: 59, name: 'BOTAŞ' },
  { id: 60, name: 'BORUSAN CAT' },
  { id: 61, name: 'BTM TEKNİK' },
  { id: 62, name: 'BURAKSAN' },
  { id: 63, name: 'CAVİTECH DENİZCİLİK' },
  { id: 64, name: 'CEYNAK' },
  { id: 65, name: 'CİHAN CENGİZ KARADENİZ GEMİ' },
  { id: 66, name: 'ÇAĞ PLAS' },
  { id: 67, name: 'ÇELİKELLER' },
  { id: 68, name: 'ÇELİKKOL' },
  { id: 69, name: 'ÇELİKOĞLU İNŞAAT' },
  { id: 70, name: 'ÇEŞME TURİZM BARTIN' },
  { id: 71, name: 'ÇETİNSA' },
  { id: 72, name: 'ÇEVİK KUVVET' },
  { id: 73, name: 'ÇİMKO' },
  { id: 74, name: 'DDR MÜHENDİSLİK' },
  { id: 75, name: 'DEHA' },
  { id: 76, name: 'DELTA LOJİSTİK' },
  { id: 77, name: 'DENAR LOJİSTİK' },
  { id: 78, name: 'DEGEM' },
  { id: 79, name: 'DENKSAN' },
  { id: 80, name: 'DH HARİTA' },
  { id: 81, name: 'DİPLOMAT GÜVENLİK' },
  { id: 82, name: 'DİANEM' },
  { id: 83, name: 'DİNÇ ELEKTRİK' },
  { id: 84, name: 'DORÇE' },
  { id: 85, name: 'DORUK ELEKTRİK' },
  { id: 86, name: 'DORUK İNŞAAT' },
  { id: 87, name: 'EDRA' },
  { id: 88, name: 'EFES MARİN' },
  { id: 89, name: 'EKA NDT' },
  { id: 90, name: 'EKE ENDÜSTRİ' },
  { id: 91, name: 'ENDOCE MÜHENDİSLİK' },
  { id: 92, name: 'ENERMECH-ENERTECH' },
  { id: 93, name: 'ENERTES' },
  { id: 94, name: 'ERAL' },
  { id: 95, name: 'ERGENÇ' },
  { id: 96, name: 'ERSOY' },
  { id: 97, name: 'ER-SU' },
  { id: 98, name: 'ERYA MÜHENDİSLİK' },
  { id: 99, name: 'ESEA' },
  { id: 100, name: 'ETA GRUP' },
  { id: 101, name: 'FATİH OFFSHORE' },
  { id: 102, name: 'FALCKON' },
  { id: 103, name: 'FIRTINA' },
  { id: 104, name: 'FİLYOS BELEDİYESİ' },
  { id: 105, name: 'FİLYOS İTFAİYE' },
  { id: 106, name: 'FİLYOS YAPI' },
  { id: 107, name: 'GALATA GRUP' },
  { id: 108, name: 'GEMA' },
  { id: 109, name: 'GEMİNİ GEMİSİ' },
  { id: 110, name: 'GEMSAN' },
  { id: 111, name: 'GİNES' },
  { id: 112, name: 'GNC TEAM' },
  { id: 113, name: 'GNR İŞ MAKİNALARI' },
  { id: 114, name: 'GNV AZZURA' },
  { id: 115, name: 'GOE PETROL' },
  { id: 116, name: 'GRM ENERJİ' },
  { id: 117, name: 'GÜN İNŞAAT' },
  { id: 118, name: 'GÜLTAŞ' },
  { id: 119, name: 'GÜNA' },
  { id: 120, name: 'GÜNGÖR ELEKTRİK' },
  { id: 121, name: 'GÜRDESAN' },
  { id: 122, name: 'GÜRAN' },
  { id: 123, name: 'GÜRAS' },
  { id: 124, name: 'HAREKET' },
  { id: 125, name: 'HEALMEDY' },
  { id: 126, name: 'HED AKADEMİ' },
  { id: 127, name: 'HCV' },
  { id: 128, name: 'HEDEF ISI' },
  { id: 129, name: 'HESA TEKNİK' },
  { id: 130, name: 'INTERCON' },
  { id: 131, name: 'IŞIKLAR AĞIR NAKLİYAT' },
  { id: 132, name: 'İKAN' },
  { id: 133, name: 'İKSA' },
  { id: 134, name: 'İMERE KÖYLÜOĞLU ENERJİ' },
  { id: 135, name: 'İMR' },
  { id: 136, name: 'İNDUNİT' },
  { id: 137, name: 'İSA AYSAN' },
  { id: 138, name: 'İSMAK' },
  { id: 139, name: 'İTFAİYE' },
  { id: 140, name: 'İZOFER' },
  { id: 141, name: 'JANDARMA' },
  { id: 142, name: 'KANUNİ GEMİSİ' },
  { id: 143, name: 'KARYAP' },
  { id: 144, name: 'KENT' },
  { id: 145, name: 'KESİR MÜHENDİSLİK' },
  { id: 146, name: 'KG PREFABRİK' },
  { id: 147, name: 'KIYI EMNİYETİ' },
  { id: 148, name: 'KIZILAY' },
  { id: 149, name: 'KIZILAY KONTEYNER' },
  { id: 150, name: 'KIZILTAŞ' },
  { id: 151, name: 'KL YAPI' },
  { id: 152, name: 'KOCABEY HAFRİYAT' },
  { id: 153, name: 'KOLİN' },
  { id: 154, name: 'KORKUT GEMİSİ' },
  { id: 155, name: 'KORTEK' },
  { id: 156, name: 'KOZTAŞ' },
  { id: 157, name: 'KSK' },
  { id: 158, name: 'KUZEY LOJİSTİK' },
  { id: 159, name: 'KUZEY MUTFAK' },
  { id: 160, name: 'KURTAŞ' },
  { id: 161, name: 'KURTOĞLU' },
  { id: 162, name: 'LAGAR' },
  { id: 163, name: 'LAM KARA-HAVA DENİZ TAŞIMACILIĞI' },
  { id: 164, name: 'LCM ROTA DENİZCİLİK' },
  { id: 165, name: 'LİVA İSKELE' },
  { id: 166, name: 'MAKİMSAN' },
  { id: 167, name: 'MAMMOET' },
  { id: 168, name: 'MANSUR İLETİŞİM' },
  { id: 169, name: 'MARE DENİZCİLİK' },
  { id: 170, name: 'MASTER NET' },
  { id: 171, name: 'MEDMARİNE' },
  { id: 172, name: 'META GRUP' },
  { id: 173, name: 'MEKTES' },
  { id: 174, name: 'MELİSA HAFRİYAT' },
  { id: 175, name: 'MERC GLOBAL' },
  { id: 176, name: 'METSAN' },
  { id: 177, name: 'MİHRİMAH GEMİSİ' },
  { id: 178, name: 'MMC GRUP' },
  { id: 179, name: 'MİM MÜHENDİSLİK' },
  { id: 180, name: 'MRM GAZİ' },
  { id: 181, name: 'MİTAŞ' },
  { id: 182, name: 'NET LAMİNAT' },
  { id: 183, name: 'NEGMAR TEKNİK DENİZCİLİK' },
  { id: 184, name: 'NOVA DENİZCİLİK' },
  { id: 185, name: 'OLCAY ENERJİ' },
  { id: 186, name: 'OGS' },
  { id: 187, name: 'OLKAR' },
  { id: 188, name: 'ONURSAN' },
  { id: 189, name: 'OPET' },
  { id: 190, name: 'OPTİMUM MÜHENDİSLİK' },
  { id: 191, name: 'ÖZARDIÇ' },
  { id: 192, name: 'ÖZDEMİR YAPI' },
  { id: 193, name: 'ÖZLEM KURUTÇU(RÖNESANS)' },
  { id: 194, name: 'PİRAMİT' },
  { id: 195, name: 'PİRENKUŞ' },
  { id: 196, name: 'POLİS' },
  { id: 197, name: 'PR BETON' },
  { id: 198, name: 'PRİZMA' },
  { id: 199, name: 'PRODA' },
  { id: 200, name: 'PRAMO' },
  { id: 201, name: 'PROTOKOL' },
  { id: 202, name: 'RET' },
  { id: 203, name: 'RASAT İSG' },
  { id: 204, name: 'ROTA MÜHENDİSLİK' },
  { id: 205, name: 'ROVTEK' },
  { id: 206, name: 'ROXANEZ GEMİSİ' },
  { id: 207, name: 'REAL' },
  { id: 208, name: 'REM GRUP' },
  { id: 209, name: 'RÖNESANS' },
  { id: 210, name: 'RYS ROTA' },
  { id: 211, name: 'SADUNOĞLU' },
  { id: 212, name: 'SABNAR' },
  { id: 213, name: 'SAHİL GÜVENLİK' },
  { id: 214, name: 'SAİPEM' },
  { id: 215, name: 'SAKARYA OFF-SHORE' },
  { id: 216, name: 'SANCAR GEMİ' },
  { id: 217, name: 'SANKO' },
  { id: 218, name: 'SARDUNYA CATERİNG' },
  { id: 219, name: 'SARIDAĞLAR' },
  { id: 220, name: 'SARILAR GRUP' },
  { id: 221, name: 'SEBA DENİZCİLİK' },
  { id: 222, name: 'SEAFORT' },
  { id: 223, name: 'SAVÇELİK' },
  { id: 224, name: 'SCHLUMBERGER' },
  { id: 225, name: 'SİSTEM VİNÇ' },
  { id: 226, name: 'SİTEPLUS' },
  { id: 227, name: 'SOLEBAY ENERJİ' },
  { id: 228, name: 'SOYSAL' },
  { id: 229, name: 'SOLİS MÜHENDİSLİK' },
  { id: 230, name: 'STEELUPRO' },
  { id: 231, name: 'SUBSEA7' },
  { id: 232, name: 'ŞADAKS' },
  { id: 233, name: 'ŞANTİYE' },
  { id: 234, name: 'TCH GRUP' },
  { id: 235, name: 'TESTKAL' },
  { id: 236, name: 'TEMSAN' },
  { id: 237, name: 'TIMS GLOBAL' },
  { id: 238, name: 'TOKA PREFABRİK' },
  { id: 239, name: 'TOKER' },
  { id: 240, name: 'TOPKAPI' },
  { id: 241, name: 'TOSYALI' },
  { id: 242, name: 'TOVER SANDAŞ İNŞAAT' },
  { id: 243, name: 'TP GÜVENLİK-EKOL GRUP' },
  { id: 244, name: 'TP-OTC' },
  { id: 245, name: 'TUNÇKAR' },
  { id: 246, name: 'TÜRK LOYDU' },
  { id: 247, name: 'TÜRK TELEKOM' },
  { id: 248, name: 'ULUER' },
  { id: 249, name: 'UNİWORKS' },
  { id: 250, name: 'UNİTED OFFSHORE' },
  { id: 251, name: 'US MÜHENDİSLİK' },
  { id: 252, name: 'ÜSTÜN ENERJİ' },
  { id: 253, name: 'VARLI PROJE' },
  { id: 254, name: 'VEMAK' },
  { id: 255, name: 'VERİTAŞ' },
  { id: 256, name: 'VİYATEK' },
  { id: 257, name: 'VOLKAN İTFAİYE' },
  { id: 258, name: 'WERNER SOBEK AG-TR' },
  { id: 259, name: 'YAREN VİNÇ' },
  { id: 260, name: 'YAŞAR AKGÜN NAKLİYAT' },
  { id: 261, name: 'YAVUZ GEMİ' },
  { id: 262, name: 'YAVUZ57' },
  { id: 263, name: 'YIKILMAZ İNŞAAT' },
  { id: 264, name: 'YİĞİTHAN PROJE' },
  { id: 265, name: 'YOKOGAVA' },
  { id: 266, name: 'YUNUS AMBULANS' },
  { id: 267, name: 'YÜKSEL TAŞ NAKLİYAT' },
  { id: 268, name: 'ZAĞANOS GEMİSİ' }
];

// Firma isimlerine göre arama için yardımcı fonksiyon
export const searchCompanies = (query) => {
  if (!query) return COMPANIES;
  const lowerQuery = query.toLowerCase();
  return COMPANIES.filter(c => c.name.toLowerCase().includes(lowerQuery));
};

// ID'ye göre firma bulma
export const getCompanyById = (id) => {
  return COMPANIES.find(c => c.id === id);
};

// İsme göre firma bulma
export const getCompanyByName = (name) => {
  return COMPANIES.find(c => c.name === name);
};

export default COMPANIES;

